### ISSUE TITLE
error

### ISSUE THREAD

**Issue by melbasuonyy** [Sraq-Zit/egygrab#1]
Hello
I'm getting this error, I'm using python 3

![image](https://user-images.githubusercontent.com/29347988/147869849-e9745037-189d-4a11-8fc2-ba5a900e18c0.png)

**Comment by Sraq-Zit** [comment]
did you specify the url ?
the command goes like this `python egygrab.py https://egybest.org/path/to/show`

**Comment by melbasuonyy** [comment]
okay.. now its working fine but another issue is up 
![image](https://user-images.githubusercontent.com/29347988/148811140-7344a66c-54be-4124-9cb8-4de865e80f0e.png)

**Comment by Sraq-Zit** [comment]
could you share with me the version you are using ?
it's inside the python file in a variable called `__version__`

**Comment by melbasuonyy** [comment]
__version__ = "1.1"

**Comment by melbasuonyy** [comment]
if not code:
                print('%s not link was available'%url)
                return (id, '')

I have deleted this lines looks ok sometimes it's stuck so I have to delete cookies folder and start again  so far it's working

**Comment by Sraq-Zit** [comment]
I'm not sure why it didn't work at first (it worked for me), but I don't recommend removing those lines, they just let you know when nothing was found

**Comment by melbasuonyy** [comment]
So After long tries, the issues is from cookies only during scrapping I keep deleting cookies files and it continue to grab the links
if you can add in your script auto delete cookies files after grabbing each season I think this issue will not happen

**Comment by melbasuonyy** [comment]
hello, could you addressed the issue please

**Comment by Sraq-Zit** [comment]
I would really like to actually reproduce the problem you have and debug it but that would take some time.
I save cookies to reuse them to avoid verification each time which takes some time especially that it goes on a couple of trials and failures.
For the time being, after updating your egygrab to 1.3.1 run it as follows:
`python egygrab.py -C <URL>`
the -C argument will tell it not to use cookies in the requests (the cookies folder will still be created, but never mind that)

**Comment by melbasuonyy** [comment]
Yes now it's working perfect thanks
