### ISSUE TITLE
Script not Working

### ISSUE THREAD

**Issue by melhadou** [Sraq-Zit/egygrab#5]
Hey, i just want to let u know that egybest enabled a new feature, to be able to download from there sites, u need to login, if it is possible we implement it in ur script. thanks in advance

**Comment by Sraq-Zit** [comment]
Hi, 
For now I see nothing changed, the script is working fine with me.
Can you support your issue with screenshot so I can understand.

As for me I can access downloads directly without logging in:
![chrome_teffIVNj3g](https://user-images.githubusercontent.com/34834428/197623758-22ce7e52-51be-4259-a777-04d8ed79cb36.gif)

And the script works fine:
![Code_hZAMJaIDYq](https://user-images.githubusercontent.com/34834428/197624507-906e44b0-09da-4d5a-815d-0a5fc792140d.gif)

**Comment by melhadou** [comment]
I'm sorry for bothering u, but its seams that it's working now. I think that egybest had some issues or something like that because in the past 3 days I've tried to download some movies, but the download links are not there, I thought that I need to log in to download them, 
again, I'm sorry for this inconvenient issue.
