### ISSUE TITLE
Script Not Working when a serie is provided

### ISSUE THREAD

**Issue by Elab4d1** [Sraq-Zit/egygrab#6]

**Comment by Sraq-Zit** [comment]
is it alright ?

**Comment by Elab4d1** [comment]
> is it alright ?

Sorry for not intended issue, i closed it because I thought it is a fault of mine. but the script is not working when i provide a serie url to the script, it generates an empty file with no download links. but it works fine when i provide a movie or an episode url.
is there anything you can do about it ?

**Comment by Sraq-Zit** [comment]
You're right!
I fixed the problem,
Thank you for reporting.
